"""added author column

Revision ID: 489d18b2e4e4
Revises: 70d5cd4f1534
Create Date: 2022-05-19 03:18:58.630427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '489d18b2e4e4'
down_revision = '70d5cd4f1534'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogpost', sa.Column('author', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogpost', 'author')
    # ### end Alembic commands ###
